include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    directives_ordering: true
    public_member_api_docs: false
    prefer_final_locals: true
    prefer_const_constructors: true
    unawaited_futures: true
